openapi: 3.1.0
info:
  title: Famly API - Family Member Removal
  version: 0.1.0
  description: Parent-managed endpoint for unlinking an existing member from a family while preserving audit history.
servers:
  - url: https://api.famly.local/v1
paths:
  /families/{familyId}/members/{memberId}:
    delete:
      summary: Remove a member from a family
      description: |
        Allows a parent in the specified family to revoke another member's access. The request is blocked if it would remove the final parent.
      security:
        - cookieAuth: []
        - bearerSession: []
        - bearerJwt: []
      parameters:
        - name: familyId
          in: path
          required: true
          description: Hex-encoded ObjectId of the family.
          schema:
            type: string
        - name: memberId
          in: path
          required: true
          description: Hex-encoded ObjectId of the member's user account.
          schema:
            type: string
      responses:
        '204':
          description: Member unlinked successfully (no response body)
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: better-auth.session_token
    bearerSession:
      type: http
      scheme: bearer
      bearerFormat: SessionToken
    bearerJwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        code:
          type: string
      required:
        - error
  responses:
    BadRequest:
      description: Invalid parameters supplied (e.g., malformed IDs)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: Caller lacks parent role for the specified family
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Member not found within the specified family
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Conflict:
      description: Removal would violate guardrails (e.g., attempting to remove the last parent)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
